version: "3.8"
services:
  app:
    build: .
    container_name: backend_doc_analyze
    ports:
      - "8000:8000"
    volumes:
      - /mnt/nfs_shared:/mnt/nfs_shared
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always