version: "3.8"

services:
  app:
    build: .
    container_name: backend_doc_analyze
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: analyze_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: analyzedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
